[package]
name = "bevy_networking_turbulence"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[features]
default = ["use-udp"]
use-udp = ["naia-server-socket/use-udp"]
use-webrtc = ["naia-server-socket/use-webrtc"]

[dependencies]
bevy = { version = "0.3", default-features = false, features = ["render"] }
turbulence = "0.3"
naia-client-socket = { version = "0.4.2", features = ["multithread"] }
bytes = "0.5"
log = "0.4"
futures-lite = "1.4"
crossbeam-channel = "0.4.4"
cfg-if = "0.1"
instant = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
naia-server-socket = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
simple_logger = "1"
rand = "0.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2"
bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2", rev = "a724cdf6b6392e3d0b185112a34c011987b8dc63"}

[[example]]
name = "balls"
path = "examples/balls.rs"
