[package]
name = "bevy_networking_turbulence"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[features]
default = ["use-udp"]
use-udp = ["naia-server-socket/use-udp"]
use-webrtc = ["naia-server-socket/use-webrtc"]

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", rev="1398d7833007e85198cfd35d5fabc70b51b4db31", default-features = false}
turbulence = "0.3"
naia-client-socket = { version = "0.4.2", features = ["multithread"] }
bytes = "0.5"
log = "0.4"
futures-lite = "1.4"
crossbeam-channel = "0.4.4"
cfg-if = "0.1"
instant = "0.1"
futures = "0.3"
futures-timer = "3.0"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
naia-server-socket = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-timer = { version = "3.0", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
simple_logger = "1"
rand = "0.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2"

[[example]]
name = "balls"
path = "examples/balls.rs"
required-features = ["bevy/default"]
